// Code generated by protoc-gen-rpcx. DO NOT EDIT.
// versions:
// - protoc-gen-rpcx v0.3.0
// - protoc          v3.16.3
// source: cryptocurrency.proto

package pb

import (
	context "context"
	client "github.com/smallnest/rpcx/client"
	protocol "github.com/smallnest/rpcx/protocol"
	server "github.com/smallnest/rpcx/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = server.NewServer
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type CryptoCurrencyAble interface {
	// CryptoCurrencyAble can be used for interface verification.

	// CryptoCurrency is server rpc method as defined
	CryptoCurrency(ctx context.Context, args *CryptoCurrencyArgs, reply *CryptoCurrencyReply) (err error)
}

// ================== server skeleton ===================
type CryptoCurrencyImpl struct{}

// ServeForCryptoCurrency starts a server only registers one service.
// You can register more services and only start one server.
// It blocks until the application exits.
func ServeForCryptoCurrency(addr string) error {
	s := server.NewServer()
	s.RegisterName("CryptoCurrency", new(CryptoCurrencyImpl), "")
	return s.Serve("tcp", addr)
}

// CryptoCurrency is server rpc method as defined
func (s *CryptoCurrencyImpl) CryptoCurrency(ctx context.Context, args *CryptoCurrencyArgs, reply *CryptoCurrencyReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = CryptoCurrencyReply{}

	return nil
}

//================== client stub ===================
// CryptoCurrency is a client wrapped XClient.
type CryptoCurrencyClient struct {
	xclient client.XClient
}

// NewCryptoCurrencyClient wraps a XClient as CryptoCurrencyClient.
// You can pass a shared XClient object created by NewXClientForCryptoCurrency.
func NewCryptoCurrencyClient(xclient client.XClient) *CryptoCurrencyClient {
	return &CryptoCurrencyClient{xclient: xclient}
}

// NewXClientForCryptoCurrency creates a XClient.
// You can configure this client with more options such as etcd registry, serialize type, select algorithm and fail mode.
func NewXClientForCryptoCurrency(addr string) (client.XClient, error) {
	d, err := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	if err != nil {
		return nil, err
	}

	opt := client.DefaultOption
	opt.SerializeType = protocol.ProtoBuffer

	xclient := client.NewXClient("CryptoCurrency", client.Failtry, client.RoundRobin, d, opt)

	return xclient, nil
}

// CryptoCurrency is client rpc method as defined
func (c *CryptoCurrencyClient) CryptoCurrency(ctx context.Context, args *CryptoCurrencyArgs) (reply *CryptoCurrencyReply, err error) {
	reply = &CryptoCurrencyReply{}
	err = c.xclient.Call(ctx, "CryptoCurrency", args, reply)
	return reply, err
}

//================== oneclient stub ===================
// CryptoCurrencyOneClient is a client wrapped oneClient.
type CryptoCurrencyOneClient struct {
	serviceName string
	oneclient   *client.OneClient
}

// NewCryptoCurrencyOneClient wraps a OneClient as CryptoCurrencyOneClient.
// You can pass a shared OneClient object created by NewOneClientForCryptoCurrency.
func NewCryptoCurrencyOneClient(oneclient *client.OneClient) *CryptoCurrencyOneClient {
	return &CryptoCurrencyOneClient{
		serviceName: "CryptoCurrency",
		oneclient:   oneclient,
	}
}

// ======================================================

// CryptoCurrency is client rpc method as defined
func (c *CryptoCurrencyOneClient) CryptoCurrency(ctx context.Context, args *CryptoCurrencyArgs) (reply *CryptoCurrencyReply, err error) {
	reply = &CryptoCurrencyReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "CryptoCurrency", args, reply)
	return reply, err
}
