// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cryptocurrency.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CryptoCurrencyArgs struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CryptoCurrencyArgs) Reset()         { *m = CryptoCurrencyArgs{} }
func (m *CryptoCurrencyArgs) String() string { return proto.CompactTextString(m) }
func (*CryptoCurrencyArgs) ProtoMessage()    {}
func (*CryptoCurrencyArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b524f72c5a77c, []int{0}
}
func (m *CryptoCurrencyArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CryptoCurrencyArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CryptoCurrencyArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CryptoCurrencyArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoCurrencyArgs.Merge(m, src)
}
func (m *CryptoCurrencyArgs) XXX_Size() int {
	return m.Size()
}
func (m *CryptoCurrencyArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoCurrencyArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoCurrencyArgs proto.InternalMessageInfo

func (m *CryptoCurrencyArgs) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type CryptoCurrencyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CryptoCurrencyReply) Reset()         { *m = CryptoCurrencyReply{} }
func (m *CryptoCurrencyReply) String() string { return proto.CompactTextString(m) }
func (*CryptoCurrencyReply) ProtoMessage()    {}
func (*CryptoCurrencyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b524f72c5a77c, []int{1}
}
func (m *CryptoCurrencyReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CryptoCurrencyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CryptoCurrencyReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CryptoCurrencyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoCurrencyReply.Merge(m, src)
}
func (m *CryptoCurrencyReply) XXX_Size() int {
	return m.Size()
}
func (m *CryptoCurrencyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoCurrencyReply.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoCurrencyReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CryptoCurrencyArgs)(nil), "pb.CryptoCurrencyArgs")
	proto.RegisterType((*CryptoCurrencyReply)(nil), "pb.CryptoCurrencyReply")
}

func init() { proto.RegisterFile("cryptocurrency.proto", fileDescriptor_ee0b524f72c5a77c) }

var fileDescriptor_ee0b524f72c5a77c = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0x4f, 0x2e, 0x2d, 0x2a, 0x4a, 0xcd, 0x4b, 0xae, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe3, 0x12, 0x72, 0x06, 0xcb, 0x39, 0x43, 0xe5, 0x1c, 0x8b,
	0xd2, 0x8b, 0x85, 0x04, 0xb8, 0x98, 0x43, 0x3d, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83,
	0x40, 0x4c, 0x25, 0x51, 0x2e, 0x61, 0x54, 0x75, 0x41, 0xa9, 0x05, 0x39, 0x95, 0x46, 0xa1, 0x5c,
	0x7c, 0xa8, 0xc2, 0x42, 0xce, 0x18, 0x22, 0x62, 0x7a, 0x05, 0x49, 0x7a, 0x98, 0x96, 0x48, 0x89,
	0x63, 0x8a, 0x83, 0x0d, 0x55, 0x62, 0x70, 0x12, 0x3b, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39,
	0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x67, 0x3c, 0x96, 0x63, 0x88, 0x62, 0xd1, 0xd3, 0x2f, 0x48, 0x4a,
	0x62, 0x03, 0x3b, 0xdc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xc1, 0xeb, 0x6b, 0xd0, 0x00,
	0x00, 0x00,
}

func (m *CryptoCurrencyArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CryptoCurrencyArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CryptoCurrencyArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.UID != 0 {
		i = encodeVarintCryptocurrency(dAtA, i, uint64(m.UID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CryptoCurrencyReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CryptoCurrencyReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CryptoCurrencyReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func encodeVarintCryptocurrency(dAtA []byte, offset int, v uint64) int {
	offset -= sovCryptocurrency(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CryptoCurrencyArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UID != 0 {
		n += 1 + sovCryptocurrency(uint64(m.UID))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CryptoCurrencyReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCryptocurrency(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCryptocurrency(x uint64) (n int) {
	return sovCryptocurrency(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CryptoCurrencyArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCryptocurrency
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CryptoCurrencyArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CryptoCurrencyArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			m.UID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCryptocurrency
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCryptocurrency(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCryptocurrency
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CryptoCurrencyReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCryptocurrency
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CryptoCurrencyReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CryptoCurrencyReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipCryptocurrency(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCryptocurrency
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCryptocurrency(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCryptocurrency
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCryptocurrency
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCryptocurrency
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCryptocurrency
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCryptocurrency
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCryptocurrency
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCryptocurrency        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCryptocurrency          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCryptocurrency = fmt.Errorf("proto: unexpected end of group")
)
