// Code generated by protoc-gen-rpcx. DO NOT EDIT.
// versions:
// - protoc-gen-rpcx v0.3.0
// - protoc          v3.16.3
// source: user.proto

package pb

import (
	context "context"
	client "github.com/smallnest/rpcx/client"
	protocol "github.com/smallnest/rpcx/protocol"
	server "github.com/smallnest/rpcx/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = server.NewServer
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type UserAble interface {
	// UserAble can be used for interface verification.

	// Register is server rpc method as defined
	Register(ctx context.Context, args *RegisterArgs, reply *RegisterReply) (err error)

	// Login is server rpc method as defined
	Login(ctx context.Context, args *LoginArgs, reply *LoginReply) (err error)

	// Logout is server rpc method as defined
	Logout(ctx context.Context, args *LogoutArgs, reply *LogoutReply) (err error)

	// ModifyAvatar is server rpc method as defined
	ModifyAvatar(ctx context.Context, args *ModifyAvatarArgs, reply *ModifyAvatarReply) (err error)

	// ModifyNickname is server rpc method as defined
	ModifyNickname(ctx context.Context, args *ModifyNicknameArgs, reply *ModifyNicknameReply) (err error)

	// ModifyPassword is server rpc method as defined
	ModifyPassword(ctx context.Context, args *ModifyPasswordArgs, reply *ModifyPasswordReply) (err error)

	// ModifyLanguage is server rpc method as defined
	ModifyLanguage(ctx context.Context, args *ModifyLanguageArgs, reply *ModifyLanguageReply) (err error)

	// ModifyUserType is server rpc method as defined
	ModifyUserType(ctx context.Context, args *ModifyUserTypeArgs, reply *ModifyUserTypeReply) (err error)

	// SetPassword is server rpc method as defined
	SetPassword(ctx context.Context, args *SetPasswordArgs, reply *SetPasswordReply) (err error)

	// ModifyBirthday is server rpc method as defined
	ModifyBirthday(ctx context.Context, args *ModifyBirthdayArgs, reply *ModifyBirthdayReply) (err error)

	// ModifyEmailVerified is server rpc method as defined
	ModifyEmailVerified(ctx context.Context, args *ModifyEmailVerifiedArgs, reply *ModifyEmailVerifiedReply) (err error)

	// ResetPassword is server rpc method as defined
	ResetPassword(ctx context.Context, args *ResetPasswordArgs, reply *ResetPasswordReply) (err error)

	// FetchUser is server rpc method as defined
	FetchUser(ctx context.Context, args *FetchUserArgs, reply *FetchUserReply) (err error)

	// FetchUserProfile is server rpc method as defined
	FetchUserProfile(ctx context.Context, args *FetchUserProfileArgs, reply *FetchUserProfileReply) (err error)

	// ExistsEmail is server rpc method as defined
	ExistsEmail(ctx context.Context, args *ExistsEmailArgs, reply *ExistsEmailReply) (err error)

	// ValidateToken is server rpc method as defined
	ValidateToken(ctx context.Context, args *ValidateTokenArgs, reply *ValidateTokenReply) (err error)

	// TelegramLogin is server rpc method as defined
	TelegramLogin(ctx context.Context, args *TelegramLoginArgs, reply *TelegramLoginReply) (err error)

	// BindEmail is server rpc method as defined
	BindEmail(ctx context.Context, args *BindEmailArgs, reply *BindEmailReply) (err error)

	// FetchInviteUrl is server rpc method as defined
	FetchInviteUrl(ctx context.Context, args *FetchInviteUrlArgs, reply *FetchInviteUrlReply) (err error)
}

// ================== server skeleton ===================
type UserImpl struct{}

// ServeForUser starts a server only registers one service.
// You can register more services and only start one server.
// It blocks until the application exits.
func ServeForUser(addr string) error {
	s := server.NewServer()
	s.RegisterName("User", new(UserImpl), "")
	return s.Serve("tcp", addr)
}

// Register is server rpc method as defined
func (s *UserImpl) Register(ctx context.Context, args *RegisterArgs, reply *RegisterReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = RegisterReply{}

	return nil
}

// Login is server rpc method as defined
func (s *UserImpl) Login(ctx context.Context, args *LoginArgs, reply *LoginReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = LoginReply{}

	return nil
}

// Logout is server rpc method as defined
func (s *UserImpl) Logout(ctx context.Context, args *LogoutArgs, reply *LogoutReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = LogoutReply{}

	return nil
}

// ModifyAvatar is server rpc method as defined
func (s *UserImpl) ModifyAvatar(ctx context.Context, args *ModifyAvatarArgs, reply *ModifyAvatarReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ModifyAvatarReply{}

	return nil
}

// ModifyNickname is server rpc method as defined
func (s *UserImpl) ModifyNickname(ctx context.Context, args *ModifyNicknameArgs, reply *ModifyNicknameReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ModifyNicknameReply{}

	return nil
}

// ModifyPassword is server rpc method as defined
func (s *UserImpl) ModifyPassword(ctx context.Context, args *ModifyPasswordArgs, reply *ModifyPasswordReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ModifyPasswordReply{}

	return nil
}

// ModifyLanguage is server rpc method as defined
func (s *UserImpl) ModifyLanguage(ctx context.Context, args *ModifyLanguageArgs, reply *ModifyLanguageReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ModifyLanguageReply{}

	return nil
}

// ModifyUserType is server rpc method as defined
func (s *UserImpl) ModifyUserType(ctx context.Context, args *ModifyUserTypeArgs, reply *ModifyUserTypeReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ModifyUserTypeReply{}

	return nil
}

// SetPassword is server rpc method as defined
func (s *UserImpl) SetPassword(ctx context.Context, args *SetPasswordArgs, reply *SetPasswordReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = SetPasswordReply{}

	return nil
}

// ModifyBirthday is server rpc method as defined
func (s *UserImpl) ModifyBirthday(ctx context.Context, args *ModifyBirthdayArgs, reply *ModifyBirthdayReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ModifyBirthdayReply{}

	return nil
}

// ModifyEmailVerified is server rpc method as defined
func (s *UserImpl) ModifyEmailVerified(ctx context.Context, args *ModifyEmailVerifiedArgs, reply *ModifyEmailVerifiedReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ModifyEmailVerifiedReply{}

	return nil
}

// ResetPassword is server rpc method as defined
func (s *UserImpl) ResetPassword(ctx context.Context, args *ResetPasswordArgs, reply *ResetPasswordReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ResetPasswordReply{}

	return nil
}

// FetchUser is server rpc method as defined
func (s *UserImpl) FetchUser(ctx context.Context, args *FetchUserArgs, reply *FetchUserReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = FetchUserReply{}

	return nil
}

// FetchUserProfile is server rpc method as defined
func (s *UserImpl) FetchUserProfile(ctx context.Context, args *FetchUserProfileArgs, reply *FetchUserProfileReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = FetchUserProfileReply{}

	return nil
}

// ExistsEmail is server rpc method as defined
func (s *UserImpl) ExistsEmail(ctx context.Context, args *ExistsEmailArgs, reply *ExistsEmailReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ExistsEmailReply{}

	return nil
}

// ValidateToken is server rpc method as defined
func (s *UserImpl) ValidateToken(ctx context.Context, args *ValidateTokenArgs, reply *ValidateTokenReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = ValidateTokenReply{}

	return nil
}

// TelegramLogin is server rpc method as defined
func (s *UserImpl) TelegramLogin(ctx context.Context, args *TelegramLoginArgs, reply *TelegramLoginReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = TelegramLoginReply{}

	return nil
}

// BindEmail is server rpc method as defined
func (s *UserImpl) BindEmail(ctx context.Context, args *BindEmailArgs, reply *BindEmailReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = BindEmailReply{}

	return nil
}

// FetchInviteUrl is server rpc method as defined
func (s *UserImpl) FetchInviteUrl(ctx context.Context, args *FetchInviteUrlArgs, reply *FetchInviteUrlReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = FetchInviteUrlReply{}

	return nil
}

//================== client stub ===================
// User is a client wrapped XClient.
type UserClient struct {
	xclient client.XClient
}

// NewUserClient wraps a XClient as UserClient.
// You can pass a shared XClient object created by NewXClientForUser.
func NewUserClient(xclient client.XClient) *UserClient {
	return &UserClient{xclient: xclient}
}

// NewXClientForUser creates a XClient.
// You can configure this client with more options such as etcd registry, serialize type, select algorithm and fail mode.
func NewXClientForUser(addr string) (client.XClient, error) {
	d, err := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	if err != nil {
		return nil, err
	}

	opt := client.DefaultOption
	opt.SerializeType = protocol.ProtoBuffer

	xclient := client.NewXClient("User", client.Failtry, client.RoundRobin, d, opt)

	return xclient, nil
}

// Register is client rpc method as defined
func (c *UserClient) Register(ctx context.Context, args *RegisterArgs) (reply *RegisterReply, err error) {
	reply = &RegisterReply{}
	err = c.xclient.Call(ctx, "Register", args, reply)
	return reply, err
}

// Login is client rpc method as defined
func (c *UserClient) Login(ctx context.Context, args *LoginArgs) (reply *LoginReply, err error) {
	reply = &LoginReply{}
	err = c.xclient.Call(ctx, "Login", args, reply)
	return reply, err
}

// Logout is client rpc method as defined
func (c *UserClient) Logout(ctx context.Context, args *LogoutArgs) (reply *LogoutReply, err error) {
	reply = &LogoutReply{}
	err = c.xclient.Call(ctx, "Logout", args, reply)
	return reply, err
}

// ModifyAvatar is client rpc method as defined
func (c *UserClient) ModifyAvatar(ctx context.Context, args *ModifyAvatarArgs) (reply *ModifyAvatarReply, err error) {
	reply = &ModifyAvatarReply{}
	err = c.xclient.Call(ctx, "ModifyAvatar", args, reply)
	return reply, err
}

// ModifyNickname is client rpc method as defined
func (c *UserClient) ModifyNickname(ctx context.Context, args *ModifyNicknameArgs) (reply *ModifyNicknameReply, err error) {
	reply = &ModifyNicknameReply{}
	err = c.xclient.Call(ctx, "ModifyNickname", args, reply)
	return reply, err
}

// ModifyPassword is client rpc method as defined
func (c *UserClient) ModifyPassword(ctx context.Context, args *ModifyPasswordArgs) (reply *ModifyPasswordReply, err error) {
	reply = &ModifyPasswordReply{}
	err = c.xclient.Call(ctx, "ModifyPassword", args, reply)
	return reply, err
}

// ModifyLanguage is client rpc method as defined
func (c *UserClient) ModifyLanguage(ctx context.Context, args *ModifyLanguageArgs) (reply *ModifyLanguageReply, err error) {
	reply = &ModifyLanguageReply{}
	err = c.xclient.Call(ctx, "ModifyLanguage", args, reply)
	return reply, err
}

// ModifyUserType is client rpc method as defined
func (c *UserClient) ModifyUserType(ctx context.Context, args *ModifyUserTypeArgs) (reply *ModifyUserTypeReply, err error) {
	reply = &ModifyUserTypeReply{}
	err = c.xclient.Call(ctx, "ModifyUserType", args, reply)
	return reply, err
}

// SetPassword is client rpc method as defined
func (c *UserClient) SetPassword(ctx context.Context, args *SetPasswordArgs) (reply *SetPasswordReply, err error) {
	reply = &SetPasswordReply{}
	err = c.xclient.Call(ctx, "SetPassword", args, reply)
	return reply, err
}

// ModifyBirthday is client rpc method as defined
func (c *UserClient) ModifyBirthday(ctx context.Context, args *ModifyBirthdayArgs) (reply *ModifyBirthdayReply, err error) {
	reply = &ModifyBirthdayReply{}
	err = c.xclient.Call(ctx, "ModifyBirthday", args, reply)
	return reply, err
}

// ModifyEmailVerified is client rpc method as defined
func (c *UserClient) ModifyEmailVerified(ctx context.Context, args *ModifyEmailVerifiedArgs) (reply *ModifyEmailVerifiedReply, err error) {
	reply = &ModifyEmailVerifiedReply{}
	err = c.xclient.Call(ctx, "ModifyEmailVerified", args, reply)
	return reply, err
}

// ResetPassword is client rpc method as defined
func (c *UserClient) ResetPassword(ctx context.Context, args *ResetPasswordArgs) (reply *ResetPasswordReply, err error) {
	reply = &ResetPasswordReply{}
	err = c.xclient.Call(ctx, "ResetPassword", args, reply)
	return reply, err
}

// FetchUser is client rpc method as defined
func (c *UserClient) FetchUser(ctx context.Context, args *FetchUserArgs) (reply *FetchUserReply, err error) {
	reply = &FetchUserReply{}
	err = c.xclient.Call(ctx, "FetchUser", args, reply)
	return reply, err
}

// FetchUserProfile is client rpc method as defined
func (c *UserClient) FetchUserProfile(ctx context.Context, args *FetchUserProfileArgs) (reply *FetchUserProfileReply, err error) {
	reply = &FetchUserProfileReply{}
	err = c.xclient.Call(ctx, "FetchUserProfile", args, reply)
	return reply, err
}

// ExistsEmail is client rpc method as defined
func (c *UserClient) ExistsEmail(ctx context.Context, args *ExistsEmailArgs) (reply *ExistsEmailReply, err error) {
	reply = &ExistsEmailReply{}
	err = c.xclient.Call(ctx, "ExistsEmail", args, reply)
	return reply, err
}

// ValidateToken is client rpc method as defined
func (c *UserClient) ValidateToken(ctx context.Context, args *ValidateTokenArgs) (reply *ValidateTokenReply, err error) {
	reply = &ValidateTokenReply{}
	err = c.xclient.Call(ctx, "ValidateToken", args, reply)
	return reply, err
}

// TelegramLogin is client rpc method as defined
func (c *UserClient) TelegramLogin(ctx context.Context, args *TelegramLoginArgs) (reply *TelegramLoginReply, err error) {
	reply = &TelegramLoginReply{}
	err = c.xclient.Call(ctx, "TelegramLogin", args, reply)
	return reply, err
}

// BindEmail is client rpc method as defined
func (c *UserClient) BindEmail(ctx context.Context, args *BindEmailArgs) (reply *BindEmailReply, err error) {
	reply = &BindEmailReply{}
	err = c.xclient.Call(ctx, "BindEmail", args, reply)
	return reply, err
}

// FetchInviteUrl is client rpc method as defined
func (c *UserClient) FetchInviteUrl(ctx context.Context, args *FetchInviteUrlArgs) (reply *FetchInviteUrlReply, err error) {
	reply = &FetchInviteUrlReply{}
	err = c.xclient.Call(ctx, "FetchInviteUrl", args, reply)
	return reply, err
}

//================== oneclient stub ===================
// UserOneClient is a client wrapped oneClient.
type UserOneClient struct {
	serviceName string
	oneclient   *client.OneClient
}

// NewUserOneClient wraps a OneClient as UserOneClient.
// You can pass a shared OneClient object created by NewOneClientForUser.
func NewUserOneClient(oneclient *client.OneClient) *UserOneClient {
	return &UserOneClient{
		serviceName: "User",
		oneclient:   oneclient,
	}
}

// ======================================================

// Register is client rpc method as defined
func (c *UserOneClient) Register(ctx context.Context, args *RegisterArgs) (reply *RegisterReply, err error) {
	reply = &RegisterReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "Register", args, reply)
	return reply, err
}

// Login is client rpc method as defined
func (c *UserOneClient) Login(ctx context.Context, args *LoginArgs) (reply *LoginReply, err error) {
	reply = &LoginReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "Login", args, reply)
	return reply, err
}

// Logout is client rpc method as defined
func (c *UserOneClient) Logout(ctx context.Context, args *LogoutArgs) (reply *LogoutReply, err error) {
	reply = &LogoutReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "Logout", args, reply)
	return reply, err
}

// ModifyAvatar is client rpc method as defined
func (c *UserOneClient) ModifyAvatar(ctx context.Context, args *ModifyAvatarArgs) (reply *ModifyAvatarReply, err error) {
	reply = &ModifyAvatarReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ModifyAvatar", args, reply)
	return reply, err
}

// ModifyNickname is client rpc method as defined
func (c *UserOneClient) ModifyNickname(ctx context.Context, args *ModifyNicknameArgs) (reply *ModifyNicknameReply, err error) {
	reply = &ModifyNicknameReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ModifyNickname", args, reply)
	return reply, err
}

// ModifyPassword is client rpc method as defined
func (c *UserOneClient) ModifyPassword(ctx context.Context, args *ModifyPasswordArgs) (reply *ModifyPasswordReply, err error) {
	reply = &ModifyPasswordReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ModifyPassword", args, reply)
	return reply, err
}

// ModifyLanguage is client rpc method as defined
func (c *UserOneClient) ModifyLanguage(ctx context.Context, args *ModifyLanguageArgs) (reply *ModifyLanguageReply, err error) {
	reply = &ModifyLanguageReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ModifyLanguage", args, reply)
	return reply, err
}

// ModifyUserType is client rpc method as defined
func (c *UserOneClient) ModifyUserType(ctx context.Context, args *ModifyUserTypeArgs) (reply *ModifyUserTypeReply, err error) {
	reply = &ModifyUserTypeReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ModifyUserType", args, reply)
	return reply, err
}

// SetPassword is client rpc method as defined
func (c *UserOneClient) SetPassword(ctx context.Context, args *SetPasswordArgs) (reply *SetPasswordReply, err error) {
	reply = &SetPasswordReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "SetPassword", args, reply)
	return reply, err
}

// ModifyBirthday is client rpc method as defined
func (c *UserOneClient) ModifyBirthday(ctx context.Context, args *ModifyBirthdayArgs) (reply *ModifyBirthdayReply, err error) {
	reply = &ModifyBirthdayReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ModifyBirthday", args, reply)
	return reply, err
}

// ModifyEmailVerified is client rpc method as defined
func (c *UserOneClient) ModifyEmailVerified(ctx context.Context, args *ModifyEmailVerifiedArgs) (reply *ModifyEmailVerifiedReply, err error) {
	reply = &ModifyEmailVerifiedReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ModifyEmailVerified", args, reply)
	return reply, err
}

// ResetPassword is client rpc method as defined
func (c *UserOneClient) ResetPassword(ctx context.Context, args *ResetPasswordArgs) (reply *ResetPasswordReply, err error) {
	reply = &ResetPasswordReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ResetPassword", args, reply)
	return reply, err
}

// FetchUser is client rpc method as defined
func (c *UserOneClient) FetchUser(ctx context.Context, args *FetchUserArgs) (reply *FetchUserReply, err error) {
	reply = &FetchUserReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "FetchUser", args, reply)
	return reply, err
}

// FetchUserProfile is client rpc method as defined
func (c *UserOneClient) FetchUserProfile(ctx context.Context, args *FetchUserProfileArgs) (reply *FetchUserProfileReply, err error) {
	reply = &FetchUserProfileReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "FetchUserProfile", args, reply)
	return reply, err
}

// ExistsEmail is client rpc method as defined
func (c *UserOneClient) ExistsEmail(ctx context.Context, args *ExistsEmailArgs) (reply *ExistsEmailReply, err error) {
	reply = &ExistsEmailReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ExistsEmail", args, reply)
	return reply, err
}

// ValidateToken is client rpc method as defined
func (c *UserOneClient) ValidateToken(ctx context.Context, args *ValidateTokenArgs) (reply *ValidateTokenReply, err error) {
	reply = &ValidateTokenReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "ValidateToken", args, reply)
	return reply, err
}

// TelegramLogin is client rpc method as defined
func (c *UserOneClient) TelegramLogin(ctx context.Context, args *TelegramLoginArgs) (reply *TelegramLoginReply, err error) {
	reply = &TelegramLoginReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "TelegramLogin", args, reply)
	return reply, err
}

// BindEmail is client rpc method as defined
func (c *UserOneClient) BindEmail(ctx context.Context, args *BindEmailArgs) (reply *BindEmailReply, err error) {
	reply = &BindEmailReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "BindEmail", args, reply)
	return reply, err
}

// FetchInviteUrl is client rpc method as defined
func (c *UserOneClient) FetchInviteUrl(ctx context.Context, args *FetchInviteUrlArgs) (reply *FetchInviteUrlReply, err error) {
	reply = &FetchInviteUrlReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "FetchInviteUrl", args, reply)
	return reply, err
}
