// Code generated by protoc-gen-rpcx. DO NOT EDIT.
// versions:
// - protoc-gen-rpcx v0.3.0
// - protoc          v3.16.3
// source: option.proto

package pb

import (
	context "context"
	client "github.com/smallnest/rpcx/client"
	protocol "github.com/smallnest/rpcx/protocol"
	server "github.com/smallnest/rpcx/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = server.NewServer
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type OptionAble interface {
	// OptionAble can be used for interface verification.

	// OptionBaseConfig is server rpc method as defined
	OptionBaseConfig(ctx context.Context, args *OptionBaseConfigArgs, reply *OptionBaseConfigReply) (err error)
}

// ================== server skeleton ===================
type OptionImpl struct{}

// ServeForOption starts a server only registers one service.
// You can register more services and only start one server.
// It blocks until the application exits.
func ServeForOption(addr string) error {
	s := server.NewServer()
	s.RegisterName("Option", new(OptionImpl), "")
	return s.Serve("tcp", addr)
}

// OptionBaseConfig is server rpc method as defined
func (s *OptionImpl) OptionBaseConfig(ctx context.Context, args *OptionBaseConfigArgs, reply *OptionBaseConfigReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = OptionBaseConfigReply{}

	return nil
}

//================== client stub ===================
// Option is a client wrapped XClient.
type OptionClient struct {
	xclient client.XClient
}

// NewOptionClient wraps a XClient as OptionClient.
// You can pass a shared XClient object created by NewXClientForOption.
func NewOptionClient(xclient client.XClient) *OptionClient {
	return &OptionClient{xclient: xclient}
}

// NewXClientForOption creates a XClient.
// You can configure this client with more options such as etcd registry, serialize type, select algorithm and fail mode.
func NewXClientForOption(addr string) (client.XClient, error) {
	d, err := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	if err != nil {
		return nil, err
	}

	opt := client.DefaultOption
	opt.SerializeType = protocol.ProtoBuffer

	xclient := client.NewXClient("Option", client.Failtry, client.RoundRobin, d, opt)

	return xclient, nil
}

// OptionBaseConfig is client rpc method as defined
func (c *OptionClient) OptionBaseConfig(ctx context.Context, args *OptionBaseConfigArgs) (reply *OptionBaseConfigReply, err error) {
	reply = &OptionBaseConfigReply{}
	err = c.xclient.Call(ctx, "OptionBaseConfig", args, reply)
	return reply, err
}

//================== oneclient stub ===================
// OptionOneClient is a client wrapped oneClient.
type OptionOneClient struct {
	serviceName string
	oneclient   *client.OneClient
}

// NewOptionOneClient wraps a OneClient as OptionOneClient.
// You can pass a shared OneClient object created by NewOneClientForOption.
func NewOptionOneClient(oneclient *client.OneClient) *OptionOneClient {
	return &OptionOneClient{
		serviceName: "Option",
		oneclient:   oneclient,
	}
}

// ======================================================

// OptionBaseConfig is client rpc method as defined
func (c *OptionOneClient) OptionBaseConfig(ctx context.Context, args *OptionBaseConfigArgs) (reply *OptionBaseConfigReply, err error) {
	reply = &OptionBaseConfigReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "OptionBaseConfig", args, reply)
	return reply, err
}
