// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: option.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OptionBaseConfigArgs struct {
	DeviceID             string   `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	DeviceType           int32    `protobuf:"varint,2,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	DeviceModel          string   `protobuf:"bytes,3,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=Country,proto3" json:"Country,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionBaseConfigArgs) Reset()         { *m = OptionBaseConfigArgs{} }
func (m *OptionBaseConfigArgs) String() string { return proto.CompactTextString(m) }
func (*OptionBaseConfigArgs) ProtoMessage()    {}
func (*OptionBaseConfigArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_6845bf9f693e8c83, []int{0}
}
func (m *OptionBaseConfigArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OptionBaseConfigArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OptionBaseConfigArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OptionBaseConfigArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionBaseConfigArgs.Merge(m, src)
}
func (m *OptionBaseConfigArgs) XXX_Size() int {
	return m.Size()
}
func (m *OptionBaseConfigArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionBaseConfigArgs.DiscardUnknown(m)
}

var xxx_messageInfo_OptionBaseConfigArgs proto.InternalMessageInfo

func (m *OptionBaseConfigArgs) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *OptionBaseConfigArgs) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *OptionBaseConfigArgs) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *OptionBaseConfigArgs) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *OptionBaseConfigArgs) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

type OptionBaseConfigReply struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	ClientIP             string   `protobuf:"bytes,3,opt,name=ClientIP,proto3" json:"ClientIP,omitempty"`
	InviteCode           string   `protobuf:"bytes,4,opt,name=InviteCode,proto3" json:"InviteCode,omitempty"`
	Channel              string   `protobuf:"bytes,5,opt,name=Channel,proto3" json:"Channel,omitempty"`
	ChannelCode          string   `protobuf:"bytes,6,opt,name=ChannelCode,proto3" json:"ChannelCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionBaseConfigReply) Reset()         { *m = OptionBaseConfigReply{} }
func (m *OptionBaseConfigReply) String() string { return proto.CompactTextString(m) }
func (*OptionBaseConfigReply) ProtoMessage()    {}
func (*OptionBaseConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6845bf9f693e8c83, []int{1}
}
func (m *OptionBaseConfigReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OptionBaseConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OptionBaseConfigReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OptionBaseConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionBaseConfigReply.Merge(m, src)
}
func (m *OptionBaseConfigReply) XXX_Size() int {
	return m.Size()
}
func (m *OptionBaseConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionBaseConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_OptionBaseConfigReply proto.InternalMessageInfo

func (m *OptionBaseConfigReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *OptionBaseConfigReply) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *OptionBaseConfigReply) GetClientIP() string {
	if m != nil {
		return m.ClientIP
	}
	return ""
}

func (m *OptionBaseConfigReply) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *OptionBaseConfigReply) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *OptionBaseConfigReply) GetChannelCode() string {
	if m != nil {
		return m.ChannelCode
	}
	return ""
}

func init() {
	proto.RegisterType((*OptionBaseConfigArgs)(nil), "pb.OptionBaseConfigArgs")
	proto.RegisterType((*OptionBaseConfigReply)(nil), "pb.OptionBaseConfigReply")
}

func init() { proto.RegisterFile("option.proto", fileDescriptor_6845bf9f693e8c83) }

var fileDescriptor_6845bf9f693e8c83 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xb3, 0x40,
	0x10, 0xc7, 0xbb, 0xfd, 0x80, 0xcf, 0x8e, 0x1e, 0xcc, 0xa6, 0x9a, 0xb5, 0x07, 0x42, 0x38, 0xf5,
	0x84, 0x89, 0x3e, 0x81, 0xa5, 0x1e, 0x38, 0x18, 0x1b, 0xf4, 0xe4, 0x0d, 0x64, 0xad, 0x9b, 0xe0,
	0xee, 0x06, 0xd6, 0x1a, 0xde, 0xc4, 0xb3, 0x6f, 0xe2, 0xcd, 0xa3, 0x8f, 0x60, 0xf0, 0x45, 0x0c,
	0x03, 0x25, 0xa4, 0xe9, 0x6d, 0x7e, 0xff, 0xc9, 0x24, 0xbf, 0x7f, 0x06, 0x8e, 0x94, 0x36, 0x42,
	0xc9, 0x40, 0x17, 0xca, 0x28, 0x3a, 0xd6, 0xa9, 0xff, 0x41, 0x60, 0x7a, 0x8b, 0xe1, 0x22, 0x29,
	0x79, 0xa8, 0xe4, 0x93, 0x58, 0x5f, 0x15, 0xeb, 0x92, 0xce, 0xe0, 0x60, 0xc9, 0x37, 0xe2, 0x91,
	0x47, 0x4b, 0x46, 0x3c, 0x32, 0x9f, 0xc4, 0x3d, 0x53, 0x17, 0xa0, 0x9d, 0xef, 0x2b, 0xcd, 0xd9,
	0xd8, 0x23, 0x73, 0x3b, 0x1e, 0x24, 0xd4, 0x83, 0xc3, 0x96, 0x6e, 0x54, 0xc6, 0x73, 0xf6, 0x0f,
	0xcf, 0x87, 0x11, 0x65, 0xf0, 0x3f, 0x54, 0xaf, 0xd2, 0x14, 0x15, 0xb3, 0x70, 0xbb, 0x45, 0x4a,
	0xc1, 0x0a, 0x85, 0xa9, 0x98, 0x8d, 0x31, 0xce, 0xfe, 0x27, 0x81, 0x93, 0x5d, 0xc9, 0x98, 0xeb,
	0xbc, 0xa2, 0x53, 0xb0, 0xaf, 0x5f, 0x12, 0x91, 0x77, 0x8a, 0x2d, 0x34, 0xee, 0xab, 0xa4, 0x2c,
	0xdf, 0x54, 0x91, 0xa1, 0xdd, 0x24, 0xee, 0xb9, 0xd9, 0x85, 0xb9, 0xe0, 0xd2, 0x44, 0xab, 0x4e,
	0xac, 0xe7, 0xa6, 0x57, 0x24, 0x37, 0xc2, 0xf0, 0x50, 0x65, 0xbc, 0x13, 0x1b, 0x24, 0x68, 0xfd,
	0x9c, 0x48, 0xc9, 0xf3, 0x4e, 0x6f, 0x8b, 0x4d, 0xe3, 0x6e, 0xc4, 0x53, 0xa7, 0x6d, 0x3c, 0x88,
	0x2e, 0xee, 0xc0, 0x69, 0x2b, 0xd0, 0x08, 0x8e, 0x77, 0xcb, 0x50, 0x16, 0xe8, 0x34, 0xd8, 0xf7,
	0x87, 0xd9, 0xd9, 0xbe, 0x0d, 0x96, 0xf7, 0x47, 0x8b, 0xd3, 0xaf, 0xda, 0x25, 0xdf, 0xb5, 0x4b,
	0x7e, 0x6a, 0x97, 0xbc, 0xff, 0xba, 0xa3, 0x07, 0x2b, 0x38, 0xd7, 0x69, 0xea, 0xe0, 0x83, 0x2f,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x79, 0x63, 0xc1, 0xc1, 0xf0, 0x01, 0x00, 0x00,
}

func (m *OptionBaseConfigArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptionBaseConfigArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OptionBaseConfigArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.City) > 0 {
		i -= len(m.City)
		copy(dAtA[i:], m.City)
		i = encodeVarintOption(dAtA, i, uint64(len(m.City)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Country) > 0 {
		i -= len(m.Country)
		copy(dAtA[i:], m.Country)
		i = encodeVarintOption(dAtA, i, uint64(len(m.Country)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DeviceModel) > 0 {
		i -= len(m.DeviceModel)
		copy(dAtA[i:], m.DeviceModel)
		i = encodeVarintOption(dAtA, i, uint64(len(m.DeviceModel)))
		i--
		dAtA[i] = 0x1a
	}
	if m.DeviceType != 0 {
		i = encodeVarintOption(dAtA, i, uint64(m.DeviceType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.DeviceID) > 0 {
		i -= len(m.DeviceID)
		copy(dAtA[i:], m.DeviceID)
		i = encodeVarintOption(dAtA, i, uint64(len(m.DeviceID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OptionBaseConfigReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptionBaseConfigReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OptionBaseConfigReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ChannelCode) > 0 {
		i -= len(m.ChannelCode)
		copy(dAtA[i:], m.ChannelCode)
		i = encodeVarintOption(dAtA, i, uint64(len(m.ChannelCode)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Channel) > 0 {
		i -= len(m.Channel)
		copy(dAtA[i:], m.Channel)
		i = encodeVarintOption(dAtA, i, uint64(len(m.Channel)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.InviteCode) > 0 {
		i -= len(m.InviteCode)
		copy(dAtA[i:], m.InviteCode)
		i = encodeVarintOption(dAtA, i, uint64(len(m.InviteCode)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ClientIP) > 0 {
		i -= len(m.ClientIP)
		copy(dAtA[i:], m.ClientIP)
		i = encodeVarintOption(dAtA, i, uint64(len(m.ClientIP)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintOption(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Email) > 0 {
		i -= len(m.Email)
		copy(dAtA[i:], m.Email)
		i = encodeVarintOption(dAtA, i, uint64(len(m.Email)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintOption(dAtA []byte, offset int, v uint64) int {
	offset -= sovOption(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OptionBaseConfigArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DeviceID)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	if m.DeviceType != 0 {
		n += 1 + sovOption(uint64(m.DeviceType))
	}
	l = len(m.DeviceModel)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	l = len(m.Country)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	l = len(m.City)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OptionBaseConfigReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	l = len(m.ClientIP)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	l = len(m.InviteCode)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	l = len(m.ChannelCode)
	if l > 0 {
		n += 1 + l + sovOption(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovOption(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOption(x uint64) (n int) {
	return sovOption(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OptionBaseConfigArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOption
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptionBaseConfigArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptionBaseConfigArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceType", wireType)
			}
			m.DeviceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeviceType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceModel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceModel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Country = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field City", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.City = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOption(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOption
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OptionBaseConfigReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOption
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptionBaseConfigReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptionBaseConfigReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InviteCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InviteCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOption(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOption
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOption(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOption
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOption
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOption
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOption
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOption
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOption
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOption        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOption          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOption = fmt.Errorf("proto: unexpected end of group")
)
