// Code generated by protoc-gen-rpcx. DO NOT EDIT.
// versions:
// - protoc-gen-rpcx v0.3.0
// - protoc          v3.16.3
// source: commission.proto

package pb

import (
	context "context"
	client "github.com/smallnest/rpcx/client"
	protocol "github.com/smallnest/rpcx/protocol"
	server "github.com/smallnest/rpcx/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = server.NewServer
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type CommissionAble interface {
	// CommissionAble can be used for interface verification.

	// FetchUserCommission is server rpc method as defined
	FetchUserCommission(ctx context.Context, args *FetchUserCommissionArgs, reply *FetchUserCommissionReply) (err error)
}

// ================== server skeleton ===================
type CommissionImpl struct{}

// ServeForCommission starts a server only registers one service.
// You can register more services and only start one server.
// It blocks until the application exits.
func ServeForCommission(addr string) error {
	s := server.NewServer()
	s.RegisterName("Commission", new(CommissionImpl), "")
	return s.Serve("tcp", addr)
}

// FetchUserCommission is server rpc method as defined
func (s *CommissionImpl) FetchUserCommission(ctx context.Context, args *FetchUserCommissionArgs, reply *FetchUserCommissionReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = FetchUserCommissionReply{}

	return nil
}

//================== client stub ===================
// Commission is a client wrapped XClient.
type CommissionClient struct {
	xclient client.XClient
}

// NewCommissionClient wraps a XClient as CommissionClient.
// You can pass a shared XClient object created by NewXClientForCommission.
func NewCommissionClient(xclient client.XClient) *CommissionClient {
	return &CommissionClient{xclient: xclient}
}

// NewXClientForCommission creates a XClient.
// You can configure this client with more options such as etcd registry, serialize type, select algorithm and fail mode.
func NewXClientForCommission(addr string) (client.XClient, error) {
	d, err := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	if err != nil {
		return nil, err
	}

	opt := client.DefaultOption
	opt.SerializeType = protocol.ProtoBuffer

	xclient := client.NewXClient("Commission", client.Failtry, client.RoundRobin, d, opt)

	return xclient, nil
}

// FetchUserCommission is client rpc method as defined
func (c *CommissionClient) FetchUserCommission(ctx context.Context, args *FetchUserCommissionArgs) (reply *FetchUserCommissionReply, err error) {
	reply = &FetchUserCommissionReply{}
	err = c.xclient.Call(ctx, "FetchUserCommission", args, reply)
	return reply, err
}

//================== oneclient stub ===================
// CommissionOneClient is a client wrapped oneClient.
type CommissionOneClient struct {
	serviceName string
	oneclient   *client.OneClient
}

// NewCommissionOneClient wraps a OneClient as CommissionOneClient.
// You can pass a shared OneClient object created by NewOneClientForCommission.
func NewCommissionOneClient(oneclient *client.OneClient) *CommissionOneClient {
	return &CommissionOneClient{
		serviceName: "Commission",
		oneclient:   oneclient,
	}
}

// ======================================================

// FetchUserCommission is client rpc method as defined
func (c *CommissionOneClient) FetchUserCommission(ctx context.Context, args *FetchUserCommissionArgs) (reply *FetchUserCommissionReply, err error) {
	reply = &FetchUserCommissionReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "FetchUserCommission", args, reply)
	return reply, err
}
