// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: commission.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchUserCommissionArgs struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchUserCommissionArgs) Reset()         { *m = FetchUserCommissionArgs{} }
func (m *FetchUserCommissionArgs) String() string { return proto.CompactTextString(m) }
func (*FetchUserCommissionArgs) ProtoMessage()    {}
func (*FetchUserCommissionArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3823d0793ff9520, []int{0}
}
func (m *FetchUserCommissionArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FetchUserCommissionArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FetchUserCommissionArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FetchUserCommissionArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchUserCommissionArgs.Merge(m, src)
}
func (m *FetchUserCommissionArgs) XXX_Size() int {
	return m.Size()
}
func (m *FetchUserCommissionArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchUserCommissionArgs.DiscardUnknown(m)
}

var xxx_messageInfo_FetchUserCommissionArgs proto.InternalMessageInfo

func (m *FetchUserCommissionArgs) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type FetchUserCommissionReply struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchUserCommissionReply) Reset()         { *m = FetchUserCommissionReply{} }
func (m *FetchUserCommissionReply) String() string { return proto.CompactTextString(m) }
func (*FetchUserCommissionReply) ProtoMessage()    {}
func (*FetchUserCommissionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3823d0793ff9520, []int{1}
}
func (m *FetchUserCommissionReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FetchUserCommissionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FetchUserCommissionReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FetchUserCommissionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchUserCommissionReply.Merge(m, src)
}
func (m *FetchUserCommissionReply) XXX_Size() int {
	return m.Size()
}
func (m *FetchUserCommissionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchUserCommissionReply.DiscardUnknown(m)
}

var xxx_messageInfo_FetchUserCommissionReply proto.InternalMessageInfo

func (m *FetchUserCommissionReply) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func init() {
	proto.RegisterType((*FetchUserCommissionArgs)(nil), "pb.FetchUserCommissionArgs")
	proto.RegisterType((*FetchUserCommissionReply)(nil), "pb.FetchUserCommissionReply")
}

func init() { proto.RegisterFile("commission.proto", fileDescriptor_a3823d0793ff9520) }

var fileDescriptor_a3823d0793ff9520 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0xcd,
	0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xd2, 0xe6, 0x12, 0x77, 0x4b, 0x2d, 0x49, 0xce, 0x08, 0x2d, 0x4e, 0x2d, 0x72, 0x86, 0x2b,
	0x70, 0x2c, 0x4a, 0x2f, 0x16, 0x12, 0xe0, 0x62, 0x0e, 0xf5, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0e, 0x02, 0x31, 0x95, 0x74, 0xb8, 0x24, 0xb0, 0x28, 0x0e, 0x4a, 0x2d, 0xc8, 0xa9, 0xc4,
	0x54, 0x6d, 0x94, 0xc0, 0xc5, 0x85, 0x50, 0x24, 0x14, 0xc4, 0x25, 0x8c, 0x45, 0xaf, 0x90, 0xb4,
	0x5e, 0x41, 0x92, 0x1e, 0x0e, 0x17, 0x48, 0xc9, 0xe0, 0x90, 0x04, 0xdb, 0xa8, 0xc4, 0xe0, 0x24,
	0x76, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0xce, 0x78, 0x2c,
	0xc7, 0x10, 0xc5, 0xa2, 0xa7, 0x5f, 0x90, 0x94, 0xc4, 0x06, 0xf6, 0x9f, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xe0, 0x4a, 0xe0, 0x32, 0xf3, 0x00, 0x00, 0x00,
}

func (m *FetchUserCommissionArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FetchUserCommissionArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FetchUserCommissionArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.UID != 0 {
		i = encodeVarintCommission(dAtA, i, uint64(m.UID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FetchUserCommissionReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FetchUserCommissionReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FetchUserCommissionReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.UID != 0 {
		i = encodeVarintCommission(dAtA, i, uint64(m.UID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommission(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommission(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FetchUserCommissionArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UID != 0 {
		n += 1 + sovCommission(uint64(m.UID))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *FetchUserCommissionReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UID != 0 {
		n += 1 + sovCommission(uint64(m.UID))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCommission(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommission(x uint64) (n int) {
	return sovCommission(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FetchUserCommissionArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FetchUserCommissionArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FetchUserCommissionArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			m.UID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCommission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FetchUserCommissionReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FetchUserCommissionReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FetchUserCommissionReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			m.UID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCommission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommission(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommission
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommission
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommission
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommission
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommission        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommission          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommission = fmt.Errorf("proto: unexpected end of group")
)
