// --------------------------------------------------------------------------------------------
// The following code is automatically generated by the mongo-dao-generator tool.
// Please do not modify this code manually to avoid being overwritten in the next generation.
// For more tool details, please click the link to view https://github.com/dobyte/gorm-dao-generator
// --------------------------------------------------------------------------------------------

package internal

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	modelpkg "xrobot/internal/model"

	"gorm.io/gorm"
)

type OrderBy struct {
	Column string
	Order  string
}

type FilterFunc func(cols *Columns) any
type UpdateFunc func(cols *Columns) any
type ColumnFunc func(cols *Columns) []string
type OrderFunc func(cols *Columns) []OrderBy

type OptionTelegramCmd struct {
	Columns   *Columns
	Database  *gorm.DB
	Table     *gorm.DB
	TableName string
}

type Columns struct {
	ChannelCode         string //渠道code
	Cmd                 string //推送方式
	CmdKind             string //推送方式
	ReplyKeyboardMarkup string
	PictureUrl          string //图片
	Type                string //文件类型(1=图片,2=视频)
	Text                string //文本内容
	ParseMode           string //编码方式
	Status              string
	OperateUid          string //
	OperateUser         string //
	CreateAt            string //
	UpdateAt            string //
}

var optionTelegramCmdColumns = &Columns{
	ChannelCode:         "channel_code", //渠道code
	Cmd:                 "cmd",          //推送方式
	CmdKind:             "cmd_kind",     //推送方式
	ReplyKeyboardMarkup: "reply_keyboard_markup",
	PictureUrl:          "picture_url", //图片
	Type:                "type",        //文件类型(1=图片,2=视频)
	Text:                "text",        //文本内容
	ParseMode:           "parse_mode",  //编码方式
	Status:              "status",
	OperateUid:          "operate_uid",  //
	OperateUser:         "operate_user", //
	CreateAt:            "created_at",   //
	UpdateAt:            "updated_at",   //
}

func NewOptionTelegramCmd(db *gorm.DB) *OptionTelegramCmd {
	dao := &OptionTelegramCmd{}
	dao.Columns = optionTelegramCmdColumns
	dao.TableName = "option_telegram_cmd"
	dao.Database = db
	dao.Table = db.Model(&modelpkg.OptionTelegramCmd{}).Table(dao.TableName)

	return dao
}

// New create a new instance and return
func (dao *OptionTelegramCmd) New(tx *gorm.DB) *OptionTelegramCmd {
	d := &OptionTelegramCmd{}
	d.Columns = dao.Columns
	d.TableName = dao.TableName
	d.Database = tx
	d.Table = tx.Model(&modelpkg.OptionTelegramCmd{}).Table(d.TableName)

	return d
}

// Insert executes an insert command to insert multiple documents into the collection.
func (dao *OptionTelegramCmd) Insert(ctx context.Context, models ...*modelpkg.OptionTelegramCmd) (int64, error) {
	if len(models) == 0 {
		return 0, errors.New("models is empty")
	}

	var rst *gorm.DB

	if len(models) == 1 {
		rst = dao.Table.WithContext(ctx).Create(models[0])
	} else {
		rst = dao.Table.WithContext(ctx).Create(models)
	}

	return rst.RowsAffected, rst.Error
}

// Delete executes a delete command to delete at most one document from the collection.
func (dao *OptionTelegramCmd) Delete(ctx context.Context, filterFunc ...FilterFunc) (int64, error) {
	db := dao.Table.WithContext(ctx)

	if len(filterFunc) > 0 && filterFunc[0] != nil {
		db = db.Where(filterFunc[0](dao.Columns))
	}

	rst := db.Delete(&modelpkg.OptionTelegramCmd{})

	return rst.RowsAffected, rst.Error
}

// Update executes an update command to update documents in the collection.
func (dao *OptionTelegramCmd) Update(ctx context.Context, filterFunc FilterFunc, updateFunc UpdateFunc) (int64, error) {
	db := dao.Table.WithContext(ctx)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if updateFunc != nil {
		rst := db.Updates(updateFunc(dao.Columns))

		return rst.RowsAffected, rst.Error
	}

	return 0, nil
}

// Count returns the number of documents in the collection.
func (dao *OptionTelegramCmd) Count(ctx context.Context, filterFunc ...FilterFunc) (count int64, err error) {
	db := dao.Table.WithContext(ctx)

	if len(filterFunc) > 0 && filterFunc[0] != nil {
		db = db.Where(filterFunc[0](dao.Columns))
	}

	err = db.Count(&count).Error

	return
}

// Sum returns the sum of the given field.
func (dao *OptionTelegramCmd) Sum(ctx context.Context, columnFunc ColumnFunc, filterFunc ...FilterFunc) (sums []float64, err error) {
	columns := columnFunc(dao.Columns)
	if len(columns) == 0 {
		return
	}

	fields := make([]string, len(columns))
	for i, column := range columns {
		fields[i] = fmt.Sprintf("COALESCE(SUM(%s), 0) as `sum_%d`", column, i)
	}

	db := dao.Table.WithContext(ctx).Select(strings.Join(fields, ","))

	if len(filterFunc) > 0 && filterFunc[0] != nil {
		db = db.Where(filterFunc[0](dao.Columns))
	}

	rst := make(map[string]any, len(columns))

	if err = db.Scan(&rst).Error; err != nil {
		return
	}

	for i := range columns {
		val, _ := rst[fmt.Sprintf("sum_%d", i)]
		sum, _ := strconv.ParseFloat(val.(string), 64)
		sums = append(sums, sum)
	}

	return
}

// Avg returns the avg of the given field.
func (dao *OptionTelegramCmd) Avg(ctx context.Context, columnFunc ColumnFunc, filterFunc ...FilterFunc) (avgs []float64, err error) {
	columns := columnFunc(dao.Columns)
	if len(columns) == 0 {
		return
	}

	fields := make([]string, len(columns))
	for i, column := range columns {
		fields[i] = fmt.Sprintf("COALESCE(AVG(%s), 0) as `avg_%d`", column, i)
	}

	db := dao.Table.WithContext(ctx).Select(strings.Join(fields, ","))

	if len(filterFunc) > 0 && filterFunc[0] != nil {
		db = db.Where(filterFunc[0](dao.Columns))
	}

	rst := make(map[string]any, len(columns))

	if err = db.Scan(&rst).Error; err != nil {
		return
	}

	for i := range columns {
		val, _ := rst[fmt.Sprintf("avg_%d", i)]
		avg, _ := strconv.ParseFloat(val.(string), 64)
		avgs = append(avgs, avg)
	}

	return
}

// First executes a first command and returns a model for one record in the table.
func (dao *OptionTelegramCmd) First(ctx context.Context, filterFunc FilterFunc, columnFunc ...ColumnFunc) (*modelpkg.OptionTelegramCmd, error) {
	var (
		model = &modelpkg.OptionTelegramCmd{}
		db    = dao.Table.WithContext(ctx)
	)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if len(columnFunc) > 0 && columnFunc[0] != nil {
		columns := columnFunc[0](dao.Columns)

		if len(columns) > 0 {
			db = db.Select(columns)
		}
	}

	if rst := db.First(model); rst.Error != nil {
		if errors.Is(rst.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, rst.Error
	}

	return model, nil
}

// Last executes a last command and returns a model for one record in the table.
func (dao *OptionTelegramCmd) Last(ctx context.Context, filterFunc FilterFunc, columnFunc ...ColumnFunc) (*modelpkg.OptionTelegramCmd, error) {
	var (
		model = &modelpkg.OptionTelegramCmd{}
		db    = dao.Table.WithContext(ctx)
	)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if len(columnFunc) > 0 && columnFunc[0] != nil {
		columns := columnFunc[0](dao.Columns)

		if len(columns) > 0 {
			db = db.Select(columns)
		}
	}

	if rst := db.Last(model); rst.Error != nil {
		if errors.Is(rst.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, rst.Error
	}

	return model, nil
}

// FindOne executes a take command and returns a model for one record in the table.
func (dao *OptionTelegramCmd) FindOne(ctx context.Context, filterFunc FilterFunc, columnFunc ...ColumnFunc) (*modelpkg.OptionTelegramCmd, error) {
	var (
		model = &modelpkg.OptionTelegramCmd{}
		db    = dao.Table.WithContext(ctx)
	)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if len(columnFunc) > 0 && columnFunc[0] != nil {
		columns := columnFunc[0](dao.Columns)

		if len(columns) > 0 {
			db = db.Select(columns)
		}
	}

	if rst := db.Take(model); rst.Error != nil {
		if errors.Is(rst.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, rst.Error
	}

	return model, nil
}

// FindMany executes a find command and returns many models the matching documents in the collection.
func (dao *OptionTelegramCmd) FindMany(ctx context.Context, filterFunc FilterFunc, columnFunc ColumnFunc, orderFunc OrderFunc, limitAndOffset ...int) ([]*modelpkg.OptionTelegramCmd, error) {
	var (
		models = make([]*modelpkg.OptionTelegramCmd, 0)
		db     = dao.Table.WithContext(ctx)
	)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if columnFunc != nil {
		columns := columnFunc(dao.Columns)

		if len(columns) > 0 {
			db = db.Select(columns)
		}
	}

	if orderFunc != nil {
		orders := orderFunc(dao.Columns)

		for _, order := range orders {
			db = db.Order(fmt.Sprintf("%s %s", order.Column, order.Order))
		}
	}

	if len(limitAndOffset) > 0 {
		db = db.Limit(limitAndOffset[0])
	}

	if len(limitAndOffset) > 1 {
		db = db.Offset(limitAndOffset[1])
	}

	rst := db.Scan(&models)

	if rst.Error != nil {
		if errors.Is(rst.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, rst.Error
	}

	return models, nil
}
