// --------------------------------------------------------------------------------------------
// The following code is automatically generated by the mongo-dao-generator tool.
// Please do not modify this code manually to avoid being overwritten in the next generation.
// For more tool details, please click the link to view https://github.com/dobyte/gorm-dao-generator
// --------------------------------------------------------------------------------------------

package internal

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	modelpkg "xrobot/internal/model"

	"gorm.io/gorm"
)

type OrderBy struct {
	Column string
	Order  string
}

type FilterFunc func(cols *Columns) any
type UpdateFunc func(cols *Columns) any
type ColumnFunc func(cols *Columns) []string
type OrderFunc func(cols *Columns) []OrderBy

type OptionTelegramKeyboardMarkupButton struct {
	Columns   *Columns
	Database  *gorm.DB
	Table     *gorm.DB
	TableName string
}

type Columns struct {
	ChannelCode     string //渠道code
	Cmd             string //推送方式                                                                        // 主键
	Text            string // 按钮的文本。如果没有使用任何可选字段，则在按钮被按下时以消息的形式发送
	LineID          string //按钮所在行
	Sort            string //按钮所在列
	RequestUsers    string // 可选。如果指定，按下按钮时将打开合适用户的列表。点击任何用户将以“users_shared”服务消息的形式将其标识符发送给机器人。仅在私聊中可用。
	RequestChat     string // 可选。如果指定，按下按钮时将打开合适聊天的列表。点击一个聊天将以“chat_shared”服务消息的形式将其标识符发送给机器人。仅在私聊中可用。
	RequestContact  string // 可选。如果为 true，用户的电话号码将在按钮被按下时作为联系人发送。仅在私聊中可用。
	RequestLocation string // 可选。如果为 true，用户的当前位置将在按钮被按下时发送。仅在私聊中可用。
	RequestPoll     string // 可选。如果指定，用户将被要求创建一个投票并在按钮被按下时发送给机器人。仅在私聊中可用。
	WebApp          string // 可选。如果指定，描述的 Web 应用将在按钮被按下时启动。Web 应用能够发送“web_app_data”服务消息。仅在私聊中可用。
	Status          string
	OperateUid      string //
	OperateUser     string //
	CreateAt        string //
	UpdateAt        string //
}

var optionTelegramKeyboardMarkupButtonColumns = &Columns{
	ChannelCode:     "channel_code",     //渠道code
	Cmd:             "cmd",              //推送方式                                                                        // 主键
	Text:            "text",             // 按钮的文本。如果没有使用任何可选字段，则在按钮被按下时以消息的形式发送
	LineID:          "line_id",          //按钮所在行
	Sort:            "sort",             //按钮所在列
	RequestUsers:    "request_users",    // 可选。如果指定，按下按钮时将打开合适用户的列表。点击任何用户将以“users_shared”服务消息的形式将其标识符发送给机器人。仅在私聊中可用。
	RequestChat:     "request_chat",     // 可选。如果指定，按下按钮时将打开合适聊天的列表。点击一个聊天将以“chat_shared”服务消息的形式将其标识符发送给机器人。仅在私聊中可用。
	RequestContact:  "request_contact",  // 可选。如果为 true，用户的电话号码将在按钮被按下时作为联系人发送。仅在私聊中可用。
	RequestLocation: "request_location", // 可选。如果为 true，用户的当前位置将在按钮被按下时发送。仅在私聊中可用。
	RequestPoll:     "request_poll",     // 可选。如果指定，用户将被要求创建一个投票并在按钮被按下时发送给机器人。仅在私聊中可用。
	WebApp:          "web_app",          // 可选。如果指定，描述的 Web 应用将在按钮被按下时启动。Web 应用能够发送“web_app_data”服务消息。仅在私聊中可用。
	Status:          "status",
	OperateUid:      "operate_uid",  //
	OperateUser:     "operate_user", //
	CreateAt:        "created_at",   //
	UpdateAt:        "updated_at",   //
}

func NewOptionTelegramKeyboardMarkupButton(db *gorm.DB) *OptionTelegramKeyboardMarkupButton {
	dao := &OptionTelegramKeyboardMarkupButton{}
	dao.Columns = optionTelegramKeyboardMarkupButtonColumns
	dao.TableName = "option_telegram_keyboard_markup_button"
	dao.Database = db
	dao.Table = db.Model(&modelpkg.OptionTelegramKeyboardMarkupButton{}).Table(dao.TableName)

	return dao
}

// New create a new instance and return
func (dao *OptionTelegramKeyboardMarkupButton) New(tx *gorm.DB) *OptionTelegramKeyboardMarkupButton {
	d := &OptionTelegramKeyboardMarkupButton{}
	d.Columns = dao.Columns
	d.TableName = dao.TableName
	d.Database = tx
	d.Table = tx.Model(&modelpkg.OptionTelegramKeyboardMarkupButton{}).Table(d.TableName)

	return d
}

// Insert executes an insert command to insert multiple documents into the collection.
func (dao *OptionTelegramKeyboardMarkupButton) Insert(ctx context.Context, models ...*modelpkg.OptionTelegramKeyboardMarkupButton) (int64, error) {
	if len(models) == 0 {
		return 0, errors.New("models is empty")
	}

	var rst *gorm.DB

	if len(models) == 1 {
		rst = dao.Table.WithContext(ctx).Create(models[0])
	} else {
		rst = dao.Table.WithContext(ctx).Create(models)
	}

	return rst.RowsAffected, rst.Error
}

// Delete executes a delete command to delete at most one document from the collection.
func (dao *OptionTelegramKeyboardMarkupButton) Delete(ctx context.Context, filterFunc ...FilterFunc) (int64, error) {
	db := dao.Table.WithContext(ctx)

	if len(filterFunc) > 0 && filterFunc[0] != nil {
		db = db.Where(filterFunc[0](dao.Columns))
	}

	rst := db.Delete(&modelpkg.OptionTelegramKeyboardMarkupButton{})

	return rst.RowsAffected, rst.Error
}

// Update executes an update command to update documents in the collection.
func (dao *OptionTelegramKeyboardMarkupButton) Update(ctx context.Context, filterFunc FilterFunc, updateFunc UpdateFunc) (int64, error) {
	db := dao.Table.WithContext(ctx)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if updateFunc != nil {
		rst := db.Updates(updateFunc(dao.Columns))

		return rst.RowsAffected, rst.Error
	}

	return 0, nil
}

// Count returns the number of documents in the collection.
func (dao *OptionTelegramKeyboardMarkupButton) Count(ctx context.Context, filterFunc ...FilterFunc) (count int64, err error) {
	db := dao.Table.WithContext(ctx)

	if len(filterFunc) > 0 && filterFunc[0] != nil {
		db = db.Where(filterFunc[0](dao.Columns))
	}

	err = db.Count(&count).Error

	return
}

// Sum returns the sum of the given field.
func (dao *OptionTelegramKeyboardMarkupButton) Sum(ctx context.Context, columnFunc ColumnFunc, filterFunc ...FilterFunc) (sums []float64, err error) {
	columns := columnFunc(dao.Columns)
	if len(columns) == 0 {
		return
	}

	fields := make([]string, len(columns))
	for i, column := range columns {
		fields[i] = fmt.Sprintf("COALESCE(SUM(%s), 0) as `sum_%d`", column, i)
	}

	db := dao.Table.WithContext(ctx).Select(strings.Join(fields, ","))

	if len(filterFunc) > 0 && filterFunc[0] != nil {
		db = db.Where(filterFunc[0](dao.Columns))
	}

	rst := make(map[string]any, len(columns))

	if err = db.Scan(&rst).Error; err != nil {
		return
	}

	for i := range columns {
		val, _ := rst[fmt.Sprintf("sum_%d", i)]
		sum, _ := strconv.ParseFloat(val.(string), 64)
		sums = append(sums, sum)
	}

	return
}

// Avg returns the avg of the given field.
func (dao *OptionTelegramKeyboardMarkupButton) Avg(ctx context.Context, columnFunc ColumnFunc, filterFunc ...FilterFunc) (avgs []float64, err error) {
	columns := columnFunc(dao.Columns)
	if len(columns) == 0 {
		return
	}

	fields := make([]string, len(columns))
	for i, column := range columns {
		fields[i] = fmt.Sprintf("COALESCE(AVG(%s), 0) as `avg_%d`", column, i)
	}

	db := dao.Table.WithContext(ctx).Select(strings.Join(fields, ","))

	if len(filterFunc) > 0 && filterFunc[0] != nil {
		db = db.Where(filterFunc[0](dao.Columns))
	}

	rst := make(map[string]any, len(columns))

	if err = db.Scan(&rst).Error; err != nil {
		return
	}

	for i := range columns {
		val, _ := rst[fmt.Sprintf("avg_%d", i)]
		avg, _ := strconv.ParseFloat(val.(string), 64)
		avgs = append(avgs, avg)
	}

	return
}

// First executes a first command and returns a model for one record in the table.
func (dao *OptionTelegramKeyboardMarkupButton) First(ctx context.Context, filterFunc FilterFunc, columnFunc ...ColumnFunc) (*modelpkg.OptionTelegramKeyboardMarkupButton, error) {
	var (
		model = &modelpkg.OptionTelegramKeyboardMarkupButton{}
		db    = dao.Table.WithContext(ctx)
	)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if len(columnFunc) > 0 && columnFunc[0] != nil {
		columns := columnFunc[0](dao.Columns)

		if len(columns) > 0 {
			db = db.Select(columns)
		}
	}

	if rst := db.First(model); rst.Error != nil {
		if errors.Is(rst.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, rst.Error
	}

	return model, nil
}

// Last executes a last command and returns a model for one record in the table.
func (dao *OptionTelegramKeyboardMarkupButton) Last(ctx context.Context, filterFunc FilterFunc, columnFunc ...ColumnFunc) (*modelpkg.OptionTelegramKeyboardMarkupButton, error) {
	var (
		model = &modelpkg.OptionTelegramKeyboardMarkupButton{}
		db    = dao.Table.WithContext(ctx)
	)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if len(columnFunc) > 0 && columnFunc[0] != nil {
		columns := columnFunc[0](dao.Columns)

		if len(columns) > 0 {
			db = db.Select(columns)
		}
	}

	if rst := db.Last(model); rst.Error != nil {
		if errors.Is(rst.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, rst.Error
	}

	return model, nil
}

// FindOne executes a take command and returns a model for one record in the table.
func (dao *OptionTelegramKeyboardMarkupButton) FindOne(ctx context.Context, filterFunc FilterFunc, columnFunc ...ColumnFunc) (*modelpkg.OptionTelegramKeyboardMarkupButton, error) {
	var (
		model = &modelpkg.OptionTelegramKeyboardMarkupButton{}
		db    = dao.Table.WithContext(ctx)
	)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if len(columnFunc) > 0 && columnFunc[0] != nil {
		columns := columnFunc[0](dao.Columns)

		if len(columns) > 0 {
			db = db.Select(columns)
		}
	}

	if rst := db.Take(model); rst.Error != nil {
		if errors.Is(rst.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, rst.Error
	}

	return model, nil
}

// FindMany executes a find command and returns many models the matching documents in the collection.
func (dao *OptionTelegramKeyboardMarkupButton) FindMany(ctx context.Context, filterFunc FilterFunc, columnFunc ColumnFunc, orderFunc OrderFunc, limitAndOffset ...int) ([]*modelpkg.OptionTelegramKeyboardMarkupButton, error) {
	var (
		models = make([]*modelpkg.OptionTelegramKeyboardMarkupButton, 0)
		db     = dao.Table.WithContext(ctx)
	)

	if filterFunc != nil {
		db = db.Where(filterFunc(dao.Columns))
	}

	if columnFunc != nil {
		columns := columnFunc(dao.Columns)

		if len(columns) > 0 {
			db = db.Select(columns)
		}
	}

	if orderFunc != nil {
		orders := orderFunc(dao.Columns)

		for _, order := range orders {
			db = db.Order(fmt.Sprintf("%s %s", order.Column, order.Order))
		}
	}

	if len(limitAndOffset) > 0 {
		db = db.Limit(limitAndOffset[0])
	}

	if len(limitAndOffset) > 1 {
		db = db.Offset(limitAndOffset[1])
	}

	rst := db.Scan(&models)

	if rst.Error != nil {
		if errors.Is(rst.Error, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, rst.Error
	}

	return models, nil
}
