// Code generated by protoc-gen-rpcx. DO NOT EDIT.
// versions:
// - protoc-gen-rpcx v0.3.0
// - protoc          v3.16.3
// source: basic.proto

package pb

import (
	context "context"
	client "github.com/smallnest/rpcx/client"
	protocol "github.com/smallnest/rpcx/protocol"
	server "github.com/smallnest/rpcx/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = server.NewServer
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type BasicAble interface {
	// BasicAble can be used for interface verification.

	// SendEmailCode is server rpc method as defined
	SendEmailCode(ctx context.Context, args *SendEmailCodeArgs, reply *SendEmailCodeReply) (err error)

	// VerifyEmailCode is server rpc method as defined
	VerifyEmailCode(ctx context.Context, args *VerifyEmailCodeArgs, reply *VerifyEmailCodeReply) (err error)
}

// ================== server skeleton ===================
type BasicImpl struct{}

// ServeForBasic starts a server only registers one service.
// You can register more services and only start one server.
// It blocks until the application exits.
func ServeForBasic(addr string) error {
	s := server.NewServer()
	s.RegisterName("Basic", new(BasicImpl), "")
	return s.Serve("tcp", addr)
}

// SendEmailCode is server rpc method as defined
func (s *BasicImpl) SendEmailCode(ctx context.Context, args *SendEmailCodeArgs, reply *SendEmailCodeReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = SendEmailCodeReply{}

	return nil
}

// VerifyEmailCode is server rpc method as defined
func (s *BasicImpl) VerifyEmailCode(ctx context.Context, args *VerifyEmailCodeArgs, reply *VerifyEmailCodeReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = VerifyEmailCodeReply{}

	return nil
}

//================== client stub ===================
// Basic is a client wrapped XClient.
type BasicClient struct {
	xclient client.XClient
}

// NewBasicClient wraps a XClient as BasicClient.
// You can pass a shared XClient object created by NewXClientForBasic.
func NewBasicClient(xclient client.XClient) *BasicClient {
	return &BasicClient{xclient: xclient}
}

// NewXClientForBasic creates a XClient.
// You can configure this client with more options such as etcd registry, serialize type, select algorithm and fail mode.
func NewXClientForBasic(addr string) (client.XClient, error) {
	d, err := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	if err != nil {
		return nil, err
	}

	opt := client.DefaultOption
	opt.SerializeType = protocol.ProtoBuffer

	xclient := client.NewXClient("Basic", client.Failtry, client.RoundRobin, d, opt)

	return xclient, nil
}

// SendEmailCode is client rpc method as defined
func (c *BasicClient) SendEmailCode(ctx context.Context, args *SendEmailCodeArgs) (reply *SendEmailCodeReply, err error) {
	reply = &SendEmailCodeReply{}
	err = c.xclient.Call(ctx, "SendEmailCode", args, reply)
	return reply, err
}

// VerifyEmailCode is client rpc method as defined
func (c *BasicClient) VerifyEmailCode(ctx context.Context, args *VerifyEmailCodeArgs) (reply *VerifyEmailCodeReply, err error) {
	reply = &VerifyEmailCodeReply{}
	err = c.xclient.Call(ctx, "VerifyEmailCode", args, reply)
	return reply, err
}

//================== oneclient stub ===================
// BasicOneClient is a client wrapped oneClient.
type BasicOneClient struct {
	serviceName string
	oneclient   *client.OneClient
}

// NewBasicOneClient wraps a OneClient as BasicOneClient.
// You can pass a shared OneClient object created by NewOneClientForBasic.
func NewBasicOneClient(oneclient *client.OneClient) *BasicOneClient {
	return &BasicOneClient{
		serviceName: "Basic",
		oneclient:   oneclient,
	}
}

// ======================================================

// SendEmailCode is client rpc method as defined
func (c *BasicOneClient) SendEmailCode(ctx context.Context, args *SendEmailCodeArgs) (reply *SendEmailCodeReply, err error) {
	reply = &SendEmailCodeReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "SendEmailCode", args, reply)
	return reply, err
}

// VerifyEmailCode is client rpc method as defined
func (c *BasicOneClient) VerifyEmailCode(ctx context.Context, args *VerifyEmailCodeArgs) (reply *VerifyEmailCodeReply, err error) {
	reply = &VerifyEmailCodeReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "VerifyEmailCode", args, reply)
	return reply, err
}
