// Code generated by protoc-gen-rpcx. DO NOT EDIT.
// versions:
// - protoc-gen-rpcx v0.3.0
// - protoc          v3.16.3
// source: wallet.proto

package pb

import (
	context "context"
	client "github.com/smallnest/rpcx/client"
	protocol "github.com/smallnest/rpcx/protocol"
	server "github.com/smallnest/rpcx/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = server.NewServer
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type WalletAble interface {
	// WalletAble can be used for interface verification.

	// InitWallet is server rpc method as defined
	InitWallet(ctx context.Context, args *InitWalletArgs, reply *InitWalletReply) (err error)

	// SetDefaultCurrency is server rpc method as defined
	SetDefaultCurrency(ctx context.Context, args *SetDefaultCurrencyArgs, reply *SetDefaultCurrencyReply) (err error)

	// IncrBalance is server rpc method as defined
	IncrBalance(ctx context.Context, args *IncrBalanceArgs, reply *IncrBalanceReply) (err error)

	// DecrBalance is server rpc method as defined
	DecrBalance(ctx context.Context, args *DecrBalanceArgs, reply *DecrBalanceReply) (err error)

	// FreezeBalance is server rpc method as defined
	FreezeBalance(ctx context.Context, args *FreezeBalanceArgs, reply *FreezeBalanceReply) (err error)

	// CancelTrade is server rpc method as defined
	CancelTrade(ctx context.Context, args *CancelTradeArgs, reply *CancelTradeReply) (err error)

	// CompleteTrade is server rpc method as defined
	CompleteTrade(ctx context.Context, args *CompleteTradeArgs, reply *CompleteTradeReply) (err error)

	// FetchBalance is server rpc method as defined
	FetchBalance(ctx context.Context, args *FetchBalanceArgs, reply *FetchBalanceReply) (err error)

	// FetchBalances is server rpc method as defined
	FetchBalances(ctx context.Context, args *FetchBalancesArgs, reply *FetchBalancesReply) (err error)

	// FetchTradeList is server rpc method as defined
	FetchTradeList(ctx context.Context, args *FetchTradeListArgs, reply *FetchTradeListReply) (err error)
}

// ================== server skeleton ===================
type WalletImpl struct{}

// ServeForWallet starts a server only registers one service.
// You can register more services and only start one server.
// It blocks until the application exits.
func ServeForWallet(addr string) error {
	s := server.NewServer()
	s.RegisterName("Wallet", new(WalletImpl), "")
	return s.Serve("tcp", addr)
}

// InitWallet is server rpc method as defined
func (s *WalletImpl) InitWallet(ctx context.Context, args *InitWalletArgs, reply *InitWalletReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = InitWalletReply{}

	return nil
}

// SetDefaultCurrency is server rpc method as defined
func (s *WalletImpl) SetDefaultCurrency(ctx context.Context, args *SetDefaultCurrencyArgs, reply *SetDefaultCurrencyReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = SetDefaultCurrencyReply{}

	return nil
}

// IncrBalance is server rpc method as defined
func (s *WalletImpl) IncrBalance(ctx context.Context, args *IncrBalanceArgs, reply *IncrBalanceReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = IncrBalanceReply{}

	return nil
}

// DecrBalance is server rpc method as defined
func (s *WalletImpl) DecrBalance(ctx context.Context, args *DecrBalanceArgs, reply *DecrBalanceReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = DecrBalanceReply{}

	return nil
}

// FreezeBalance is server rpc method as defined
func (s *WalletImpl) FreezeBalance(ctx context.Context, args *FreezeBalanceArgs, reply *FreezeBalanceReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = FreezeBalanceReply{}

	return nil
}

// CancelTrade is server rpc method as defined
func (s *WalletImpl) CancelTrade(ctx context.Context, args *CancelTradeArgs, reply *CancelTradeReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = CancelTradeReply{}

	return nil
}

// CompleteTrade is server rpc method as defined
func (s *WalletImpl) CompleteTrade(ctx context.Context, args *CompleteTradeArgs, reply *CompleteTradeReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = CompleteTradeReply{}

	return nil
}

// FetchBalance is server rpc method as defined
func (s *WalletImpl) FetchBalance(ctx context.Context, args *FetchBalanceArgs, reply *FetchBalanceReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = FetchBalanceReply{}

	return nil
}

// FetchBalances is server rpc method as defined
func (s *WalletImpl) FetchBalances(ctx context.Context, args *FetchBalancesArgs, reply *FetchBalancesReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = FetchBalancesReply{}

	return nil
}

// FetchTradeList is server rpc method as defined
func (s *WalletImpl) FetchTradeList(ctx context.Context, args *FetchTradeListArgs, reply *FetchTradeListReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = FetchTradeListReply{}

	return nil
}

//================== client stub ===================
// Wallet is a client wrapped XClient.
type WalletClient struct {
	xclient client.XClient
}

// NewWalletClient wraps a XClient as WalletClient.
// You can pass a shared XClient object created by NewXClientForWallet.
func NewWalletClient(xclient client.XClient) *WalletClient {
	return &WalletClient{xclient: xclient}
}

// NewXClientForWallet creates a XClient.
// You can configure this client with more options such as etcd registry, serialize type, select algorithm and fail mode.
func NewXClientForWallet(addr string) (client.XClient, error) {
	d, err := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	if err != nil {
		return nil, err
	}

	opt := client.DefaultOption
	opt.SerializeType = protocol.ProtoBuffer

	xclient := client.NewXClient("Wallet", client.Failtry, client.RoundRobin, d, opt)

	return xclient, nil
}

// InitWallet is client rpc method as defined
func (c *WalletClient) InitWallet(ctx context.Context, args *InitWalletArgs) (reply *InitWalletReply, err error) {
	reply = &InitWalletReply{}
	err = c.xclient.Call(ctx, "InitWallet", args, reply)
	return reply, err
}

// SetDefaultCurrency is client rpc method as defined
func (c *WalletClient) SetDefaultCurrency(ctx context.Context, args *SetDefaultCurrencyArgs) (reply *SetDefaultCurrencyReply, err error) {
	reply = &SetDefaultCurrencyReply{}
	err = c.xclient.Call(ctx, "SetDefaultCurrency", args, reply)
	return reply, err
}

// IncrBalance is client rpc method as defined
func (c *WalletClient) IncrBalance(ctx context.Context, args *IncrBalanceArgs) (reply *IncrBalanceReply, err error) {
	reply = &IncrBalanceReply{}
	err = c.xclient.Call(ctx, "IncrBalance", args, reply)
	return reply, err
}

// DecrBalance is client rpc method as defined
func (c *WalletClient) DecrBalance(ctx context.Context, args *DecrBalanceArgs) (reply *DecrBalanceReply, err error) {
	reply = &DecrBalanceReply{}
	err = c.xclient.Call(ctx, "DecrBalance", args, reply)
	return reply, err
}

// FreezeBalance is client rpc method as defined
func (c *WalletClient) FreezeBalance(ctx context.Context, args *FreezeBalanceArgs) (reply *FreezeBalanceReply, err error) {
	reply = &FreezeBalanceReply{}
	err = c.xclient.Call(ctx, "FreezeBalance", args, reply)
	return reply, err
}

// CancelTrade is client rpc method as defined
func (c *WalletClient) CancelTrade(ctx context.Context, args *CancelTradeArgs) (reply *CancelTradeReply, err error) {
	reply = &CancelTradeReply{}
	err = c.xclient.Call(ctx, "CancelTrade", args, reply)
	return reply, err
}

// CompleteTrade is client rpc method as defined
func (c *WalletClient) CompleteTrade(ctx context.Context, args *CompleteTradeArgs) (reply *CompleteTradeReply, err error) {
	reply = &CompleteTradeReply{}
	err = c.xclient.Call(ctx, "CompleteTrade", args, reply)
	return reply, err
}

// FetchBalance is client rpc method as defined
func (c *WalletClient) FetchBalance(ctx context.Context, args *FetchBalanceArgs) (reply *FetchBalanceReply, err error) {
	reply = &FetchBalanceReply{}
	err = c.xclient.Call(ctx, "FetchBalance", args, reply)
	return reply, err
}

// FetchBalances is client rpc method as defined
func (c *WalletClient) FetchBalances(ctx context.Context, args *FetchBalancesArgs) (reply *FetchBalancesReply, err error) {
	reply = &FetchBalancesReply{}
	err = c.xclient.Call(ctx, "FetchBalances", args, reply)
	return reply, err
}

// FetchTradeList is client rpc method as defined
func (c *WalletClient) FetchTradeList(ctx context.Context, args *FetchTradeListArgs) (reply *FetchTradeListReply, err error) {
	reply = &FetchTradeListReply{}
	err = c.xclient.Call(ctx, "FetchTradeList", args, reply)
	return reply, err
}

//================== oneclient stub ===================
// WalletOneClient is a client wrapped oneClient.
type WalletOneClient struct {
	serviceName string
	oneclient   *client.OneClient
}

// NewWalletOneClient wraps a OneClient as WalletOneClient.
// You can pass a shared OneClient object created by NewOneClientForWallet.
func NewWalletOneClient(oneclient *client.OneClient) *WalletOneClient {
	return &WalletOneClient{
		serviceName: "Wallet",
		oneclient:   oneclient,
	}
}

// ======================================================

// InitWallet is client rpc method as defined
func (c *WalletOneClient) InitWallet(ctx context.Context, args *InitWalletArgs) (reply *InitWalletReply, err error) {
	reply = &InitWalletReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "InitWallet", args, reply)
	return reply, err
}

// SetDefaultCurrency is client rpc method as defined
func (c *WalletOneClient) SetDefaultCurrency(ctx context.Context, args *SetDefaultCurrencyArgs) (reply *SetDefaultCurrencyReply, err error) {
	reply = &SetDefaultCurrencyReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "SetDefaultCurrency", args, reply)
	return reply, err
}

// IncrBalance is client rpc method as defined
func (c *WalletOneClient) IncrBalance(ctx context.Context, args *IncrBalanceArgs) (reply *IncrBalanceReply, err error) {
	reply = &IncrBalanceReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "IncrBalance", args, reply)
	return reply, err
}

// DecrBalance is client rpc method as defined
func (c *WalletOneClient) DecrBalance(ctx context.Context, args *DecrBalanceArgs) (reply *DecrBalanceReply, err error) {
	reply = &DecrBalanceReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "DecrBalance", args, reply)
	return reply, err
}

// FreezeBalance is client rpc method as defined
func (c *WalletOneClient) FreezeBalance(ctx context.Context, args *FreezeBalanceArgs) (reply *FreezeBalanceReply, err error) {
	reply = &FreezeBalanceReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "FreezeBalance", args, reply)
	return reply, err
}

// CancelTrade is client rpc method as defined
func (c *WalletOneClient) CancelTrade(ctx context.Context, args *CancelTradeArgs) (reply *CancelTradeReply, err error) {
	reply = &CancelTradeReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "CancelTrade", args, reply)
	return reply, err
}

// CompleteTrade is client rpc method as defined
func (c *WalletOneClient) CompleteTrade(ctx context.Context, args *CompleteTradeArgs) (reply *CompleteTradeReply, err error) {
	reply = &CompleteTradeReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "CompleteTrade", args, reply)
	return reply, err
}

// FetchBalance is client rpc method as defined
func (c *WalletOneClient) FetchBalance(ctx context.Context, args *FetchBalanceArgs) (reply *FetchBalanceReply, err error) {
	reply = &FetchBalanceReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "FetchBalance", args, reply)
	return reply, err
}

// FetchBalances is client rpc method as defined
func (c *WalletOneClient) FetchBalances(ctx context.Context, args *FetchBalancesArgs) (reply *FetchBalancesReply, err error) {
	reply = &FetchBalancesReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "FetchBalances", args, reply)
	return reply, err
}

// FetchTradeList is client rpc method as defined
func (c *WalletOneClient) FetchTradeList(ctx context.Context, args *FetchTradeListArgs) (reply *FetchTradeListReply, err error) {
	reply = &FetchTradeListReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "FetchTradeList", args, reply)
	return reply, err
}
