// Code generated by protoc-gen-rpcx. DO NOT EDIT.
// versions:
// - protoc-gen-rpcx v0.3.0
// - protoc          v3.16.3
// source: business.proto

package pb

import (
	context "context"
	client "github.com/smallnest/rpcx/client"
	protocol "github.com/smallnest/rpcx/protocol"
	server "github.com/smallnest/rpcx/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.TODO
var _ = server.NewServer
var _ = client.NewClient
var _ = protocol.NewMessage

// ================== interface skeleton ===================
type BusinessAble interface {
	// BusinessAble can be used for interface verification.

	// Business is server rpc method as defined
	Business(ctx context.Context, args *BusinessArgs, reply *BusinessReply) (err error)
}

// ================== server skeleton ===================
type BusinessImpl struct{}

// ServeForBusiness starts a server only registers one service.
// You can register more services and only start one server.
// It blocks until the application exits.
func ServeForBusiness(addr string) error {
	s := server.NewServer()
	s.RegisterName("Business", new(BusinessImpl), "")
	return s.Serve("tcp", addr)
}

// Business is server rpc method as defined
func (s *BusinessImpl) Business(ctx context.Context, args *BusinessArgs, reply *BusinessReply) (err error) {
	// TODO: add business logics

	// TODO: setting return values
	*reply = BusinessReply{}

	return nil
}

//================== client stub ===================
// Business is a client wrapped XClient.
type BusinessClient struct {
	xclient client.XClient
}

// NewBusinessClient wraps a XClient as BusinessClient.
// You can pass a shared XClient object created by NewXClientForBusiness.
func NewBusinessClient(xclient client.XClient) *BusinessClient {
	return &BusinessClient{xclient: xclient}
}

// NewXClientForBusiness creates a XClient.
// You can configure this client with more options such as etcd registry, serialize type, select algorithm and fail mode.
func NewXClientForBusiness(addr string) (client.XClient, error) {
	d, err := client.NewPeer2PeerDiscovery("tcp@"+addr, "")
	if err != nil {
		return nil, err
	}

	opt := client.DefaultOption
	opt.SerializeType = protocol.ProtoBuffer

	xclient := client.NewXClient("Business", client.Failtry, client.RoundRobin, d, opt)

	return xclient, nil
}

// Business is client rpc method as defined
func (c *BusinessClient) Business(ctx context.Context, args *BusinessArgs) (reply *BusinessReply, err error) {
	reply = &BusinessReply{}
	err = c.xclient.Call(ctx, "Business", args, reply)
	return reply, err
}

//================== oneclient stub ===================
// BusinessOneClient is a client wrapped oneClient.
type BusinessOneClient struct {
	serviceName string
	oneclient   *client.OneClient
}

// NewBusinessOneClient wraps a OneClient as BusinessOneClient.
// You can pass a shared OneClient object created by NewOneClientForBusiness.
func NewBusinessOneClient(oneclient *client.OneClient) *BusinessOneClient {
	return &BusinessOneClient{
		serviceName: "Business",
		oneclient:   oneclient,
	}
}

// ======================================================

// Business is client rpc method as defined
func (c *BusinessOneClient) Business(ctx context.Context, args *BusinessArgs) (reply *BusinessReply, err error) {
	reply = &BusinessReply{}
	err = c.oneclient.Call(ctx, c.serviceName, "Business", args, reply)
	return reply, err
}
